import 'timeseri.dart';

class Autogenerated {
  List<TimeSeri> afghanistan;

  Autogenerated({
    this.afghanistan,
    
  });

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
        afghanistan : json['Afghanistan'] != null ? json['Afghanistan'].map<TimeSeri>((json) => TimeSeri.fromJson(json))
        .toList(growable: false): null
  );
    /*if (json['Afghanistan'] != null) {
      afghanistan = new List<TimeSeri>();
      json['Afghanistan'].forEach((v) {
        afghanistan.add(new TimeSeri.fromJson(v));
      });
    }*/
}
}