import 'timeseri.dart';

class Autogenerated {
  List<TimeSeri> afghanistan;
  List<TimeSeri> albania;
  List<TimeSeri> algeria;
  List<TimeSeri> andorra;
  List<TimeSeri> angola;
  List<TimeSeri> antigua;
  List<TimeSeri> argentina;
  List<TimeSeri> armenia;
  List<TimeSeri> australia;
  List<TimeSeri> austria;
  List<TimeSeri> azerbaijan;
  List<TimeSeri> bahamas;
  List<TimeSeri> bahrain;
  List<TimeSeri> bangladesh;
  List<TimeSeri> barbados;
  List<TimeSeri> belarus;
  List<TimeSeri> belgium;
  List<TimeSeri> benin;
  List<TimeSeri> bhutan;
  List<TimeSeri> bolivia;
  List<TimeSeri> bosnia;
  List<TimeSeri> brazil;
  List<TimeSeri> brunei;
  List<TimeSeri> bulgaria;
  List<TimeSeri> burkina;
  List<TimeSeri> cabo;
  List<TimeSeri> cambodia;
  List<TimeSeri> cameroon;
  List<TimeSeri> canada;
  List<TimeSeri> central;
  List<TimeSeri> chad;
  List<TimeSeri> chile;
  List<TimeSeri> china;
  List<TimeSeri> colombia;
  List<TimeSeri> congobrazzaville;
  List<TimeSeri> congokinshasa;
  List<TimeSeri> costa;
  List<TimeSeri> cote;
  List<TimeSeri> croatia;
  List<TimeSeri> diamond;
  List<TimeSeri> cuba;
  List<TimeSeri> cyprus;
  List<TimeSeri> czechia;
  List<TimeSeri> denmark;
  List<TimeSeri> djibouti;
  List<TimeSeri> dominican;
  List<TimeSeri> ecuador;
  List<TimeSeri> egypt;
  List<TimeSeri> el;
  List<TimeSeri> equatorial;
  List<TimeSeri> eritrea;
  List<TimeSeri> estonia;
  List<TimeSeri> eswatini;
  List<TimeSeri> ethiopia;
  List<TimeSeri> fiji;
  List<TimeSeri> finland;
  List<TimeSeri> france;
  List<TimeSeri> gabon;
  List<TimeSeri> gambia;
  List<TimeSeri> georgia;
  List<TimeSeri> germany;
  List<TimeSeri> ghana;
  List<TimeSeri> greece;
  List<TimeSeri> guatemala;
  List<TimeSeri> guinea;
  List<TimeSeri> guyana;
  List<TimeSeri> haiti;
  List<TimeSeri> holy;
  List<TimeSeri> honduras;
  List<TimeSeri> hungary;
  List<TimeSeri> iceland;
  List<TimeSeri> india;
  List<TimeSeri> indonesia;
  List<TimeSeri> iran;
  List<TimeSeri> iraq;
  List<TimeSeri> ireland;
  List<TimeSeri> israel;
  List<TimeSeri> italy;
  List<TimeSeri> jamaica;
  List<TimeSeri> japan;
  List<TimeSeri> jordan;
  List<TimeSeri> kazakhstan;
  List<TimeSeri> kenya;
  List<TimeSeri> korea;
  List<TimeSeri> kuwait;
  List<TimeSeri> kyrgyzstan;
  List<TimeSeri> latvia;
  List<TimeSeri> lebanon;
  List<TimeSeri> liberia;
  List<TimeSeri> liechtenstein;
  List<TimeSeri> lithuania;
  List<TimeSeri> luxembourg;
  List<TimeSeri> madagascar;
  List<TimeSeri> malaysia;
  List<TimeSeri> maldives;
  List<TimeSeri> malta;
  List<TimeSeri> mauritania;
  List<TimeSeri> mauritius;
  List<TimeSeri> mexico;
  List<TimeSeri> moldova;
  List<TimeSeri> monaco;
  List<TimeSeri> mongolia;
  List<TimeSeri> montenegro;
  List<TimeSeri> morocco;
  List<TimeSeri> namibia;
  List<TimeSeri> nepal;
  List<TimeSeri> netherlands;
  List<TimeSeri> newzealand;
  List<TimeSeri> nicaragua;
  List<TimeSeri> niger;
  List<TimeSeri> nigeria;
  List<TimeSeri> north;
  List<TimeSeri> norway;
  List<TimeSeri> oman;
  List<TimeSeri> pakistan;
  List<TimeSeri> panama;
  List<TimeSeri> papua;
  List<TimeSeri> paraguay;
  List<TimeSeri> peru;
  List<TimeSeri> philippines;
  List<TimeSeri> poland;
  List<TimeSeri> portugal;
  List<TimeSeri> qatar;
  List<TimeSeri> romania;
  List<TimeSeri> russia;
  List<TimeSeri> rwanda;
  List<TimeSeri> saintlucia;
  List<TimeSeri> saintvincentgrenadines;
  List<TimeSeri> san;
  List<TimeSeri> saudi;
  List<TimeSeri> senegal;
  List<TimeSeri> serbia;
  List<TimeSeri> seychelles;
  List<TimeSeri> singapore;
  List<TimeSeri> slovakia;
  List<TimeSeri> slovenia;
  List<TimeSeri> somalia;
  List<TimeSeri> south;
  List<TimeSeri> spain;
  List<TimeSeri> sri;
  List<TimeSeri> sudan;
  List<TimeSeri> suriname;
  List<TimeSeri> sweden;
  List<TimeSeri> switzerland;
  List<TimeSeri> taiwan;
  List<TimeSeri> tanzania;
  List<TimeSeri> thailand;
  List<TimeSeri> togo;
  List<TimeSeri> trinidad;
  List<TimeSeri> tunisia;
  List<TimeSeri> turkey;
  List<TimeSeri> uganda;
  List<TimeSeri> ukraine;
  List<TimeSeri> unitedarab;
  List<TimeSeri> unitedkingdom;
  List<TimeSeri> uruguay;
  List<TimeSeri> us;
  List<TimeSeri> uzbekistan;
  List<TimeSeri> venezuela;
  List<TimeSeri> vietnam;
  List<TimeSeri> zambia;
  List<TimeSeri> zimbabwe;
  List<TimeSeri> dominica;
  List<TimeSeri> grenada;
  List<TimeSeri> mozambique;
  List<TimeSeri> syria;
  List<TimeSeri> timorleste;
  List<TimeSeri> belize;
  List<TimeSeri> laos;
  List<TimeSeri> libya;
  List<TimeSeri> west;
  List<TimeSeri> guineabissau;
  List<TimeSeri> mali;
  List<TimeSeri> saint;
  List<TimeSeri> kosovo;
  List<TimeSeri> burma;
  List<TimeSeri> ms;
  List<TimeSeri> botswana;
  List<TimeSeri> burundi;
  List<TimeSeri> sierra;
  List<TimeSeri> malawi;
  List<TimeSeri> southsudan;
  List<TimeSeri> western;
  List<TimeSeri> sao;
  List<TimeSeri> yemen;
  List<TimeSeri> comoros;
  List<TimeSeri> tajikistan;
  List<TimeSeri> lesotho;

  Autogenerated({
    this.afghanistan,
    this.albania,
    this.algeria,
    this.andorra,
    this.angola,
    this.antigua,
    this.argentina,
    this.armenia,
    this.australia,
    this.austria,
    this.azerbaijan,
    this.bahamas,
    this.bahrain,
    this.bangladesh,
    this.barbados,
    this.belarus,
    this.belgium,
    this.benin,
    this.bhutan,
    this.bolivia,
    this.bosnia,
    this.brazil,
    this.brunei,
    this.bulgaria,
    this.burkina,
    this.cabo,
    this.cambodia,
    this.cameroon,
    this.canada,
    this.central,
    this.chad,
    this.chile,
    this.china,
    this.colombia,
    this.congobrazzaville,
    this.congokinshasa,
    this.costa,
    this.cote,
    this.croatia,
    this.diamond,
    this.cuba,
    this.cyprus,
    this.czechia,
    this.denmark,
    this.djibouti,
    this.dominican,
    this.ecuador,
    this.egypt,
    this.el,
    this.equatorial,
    this.eritrea,
    this.estonia,
    this.eswatini,
    this.ethiopia,
    this.fiji,
    this.finland,
    this.france,
    this.gabon,
    this.gambia,
    this.georgia,
    this.germany,
    this.ghana,
    this.greece,
    this.guatemala,
    this.guinea,
    this.guyana,
    this.haiti,
    this.holy,
    this.honduras,
    this.hungary,
    this.iceland,
    this.india,
    this.indonesia,
    this.iran,
    this.iraq,
    this.ireland,
    this.israel,
    this.italy,
    this.jamaica,
    this.japan,
    this.jordan,
    this.kazakhstan,
    this.kenya,
    this.korea,
    this.kuwait,
    this.kyrgyzstan,
    this.latvia,
    this.lebanon,
    this.liberia,
    this.liechtenstein,
    this.lithuania,
    this.luxembourg,
    this.madagascar,
    this.malaysia,
    this.maldives,
    this.malta,
    this.mauritania,
    this.mauritius,
    this.mexico,
    this.moldova,
    this.monaco,
    this.mongolia,
    this.montenegro,
    this.morocco,
    this.namibia,
    this.nepal,
    this.netherlands,
    this.newzealand,
    this.nicaragua,
    this.niger,
    this.nigeria,
    this.north,
    this.norway,
    this.oman,
    this.pakistan,
    this.panama,
    this.papua,
    this.paraguay,
    this.peru,
    this.philippines,
    this.poland,
    this.portugal,
    this.qatar,
    this.romania,
    this.russia,
    this.rwanda,
    this.saint,
    this.saint,
    this.san,
    this.saudi,
    this.senegal,
    this.serbia,
    this.seychelles,
    this.singapore,
    this.slovakia,
    this.slovenia,
    this.somalia,
    this.south,
    this.spain,
    this.sri,
    this.sudan,
    this.suriname,
    this.sweden,
    this.switzerland,
    this.taiwan,
    this.tanzania,
    this.thailand,
    this.togo,
    this.trinidad,
    this.tunisia,
    this.turkey,
    this.uganda,
    this.ukraine,
    this.unitedarab,
    this.unitedkingdom,
    this.uruguay,
    this.us,
    this.uzbekistan,
    this.venezuela,
    this.vietnam,
    this.zambia,
    this.zimbabwe,
    this.dominica,
    this.grenada,
    this.mozambique,
    this.syria,
    this.timorleste,
    this.belize,
    this.laos,
    this.libya,
    this.west,
    this.guineabissau,
    this.mali,
    this.saint,
    this.kosovo,
    this.burma,
    this.ms,
    this.botswana,
    this.burundi,
    this.sierra,
    this.malawi,
    this.south,
    this.western,
    this.sao,
    this.yemen,
    this.comoros,
    this.tajikistan,
    this.lesotho,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['Afghanistan'] != null) {
      afghanistan = new List<TimeSeri>();
      json['Afghanistan'].forEach((v) {
        afghanistan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Albania'] != null) {
      albania = new List<TimeSeri>();
      json['Albania'].forEach((v) {
        albania.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Algeria'] != null) {
      algeria = new List<TimeSeri>();
      json['Algeria'].forEach((v) {
        algeria.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Andorra'] != null) {
      andorra = new List<TimeSeri>();
      json['Andorra'].forEach((v) {
        andorra.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Angola'] != null) {
      angola = new List<TimeSeri>();
      json['Angola'].forEach((v) {
        angola.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Antigua and Barbuda'] != null) {
      antigua = new List<TimeSeri>();
      json['Antigua and Barbuda'].forEach((v) {
        antigua.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Argentina'] != null) {
      argentina = new List<TimeSeri>();
      json['Argentina'].forEach((v) {
        argentina.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Armenia'] != null) {
      armenia = new List<TimeSeri>();
      json['Armenia'].forEach((v) {
        armenia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Australia'] != null) {
      australia = new List<TimeSeri>();
      json['Australia'].forEach((v) {
        australia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Austria'] != null) {
      austria = new List<TimeSeri>();
      json['Austria'].forEach((v) {
        austria.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Azerbaijan'] != null) {
      azerbaijan = new List<TimeSeri>();
      json['Azerbaijan'].forEach((v) {
        azerbaijan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Bahamas'] != null) {
      bahamas = new List<TimeSeri>();
      json['Bahamas'].forEach((v) {
        bahamas.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Bahrain'] != null) {
      bahrain = new List<TimeSeri>();
      json['Bahrain'].forEach((v) {
        bahrain.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Bangladesh'] != null) {
      bangladesh = new List<TimeSeri>();
      json['Bangladesh'].forEach((v) {
        bangladesh.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Barbados'] != null) {
      barbados = new List<TimeSeri>();
      json['Barbados'].forEach((v) {
        barbados.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Belarus'] != null) {
      belarus = new List<TimeSeri>();
      json['Belarus'].forEach((v) {
        belarus.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Belgium'] != null) {
      belgium = new List<TimeSeri>();
      json['Belgium'].forEach((v) {
        belgium.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Benin'] != null) {
      benin = new List<TimeSeri>();
      json['Benin'].forEach((v) {
        benin.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Bhutan'] != null) {
      bhutan = new List<TimeSeri>();
      json['Bhutan'].forEach((v) {
        bhutan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Bolivia'] != null) {
      bolivia = new List<TimeSeri>();
      json['Bolivia'].forEach((v) {
        bolivia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Bosnia and Herzegovina'] != null) {
      bosnia = new List<TimeSeri>();
      json['Bosnia and Herzegovina'].forEach((v) {
        bosnia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Brazil'] != null) {
      brazil = new List<TimeSeri>();
      json['Brazil'].forEach((v) {
        brazil.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Brunei'] != null) {
      brunei = new List<TimeSeri>();
      json['Brunei'].forEach((v) {
        brunei.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Bulgaria'] != null) {
      bulgaria = new List<TimeSeri>();
      json['Bulgaria'].forEach((v) {
        bulgaria.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Burkina Faso'] != null) {
      burkina = new List<TimeSeri>();
      json['Burkina Faso'].forEach((v) {
        burkina.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Cabo Verde'] != null) {
      cabo = new List<TimeSeri>();
      json['Cabo Verde'].forEach((v) {
        cabo.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Cambodia'] != null) {
      cambodia = new List<TimeSeri>();
      json['Cambodia'].forEach((v) {
        cambodia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Cameroon'] != null) {
      cameroon = new List<TimeSeri>();
      json['Cameroon'].forEach((v) {
        cameroon.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Canada'] != null) {
      canada = new List<TimeSeri>();
      json['Canada'].forEach((v) {
        canada.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Central African Republic'] != null) {
      central = new List<TimeSeri>();
      json['Central African Republic'].forEach((v) {
        central.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Chad'] != null) {
      chad = new List<TimeSeri>();
      json['Chad'].forEach((v) {
        chad.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Chile'] != null) {
      chile = new List<TimeSeri>();
      json['Chile'].forEach((v) {
        chile.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['China'] != null) {
      china = new List<TimeSeri>();
      json['China'].forEach((v) {
        china.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Colombia'] != null) {
      colombia = new List<TimeSeri>();
      json['Colombia'].forEach((v) {
        colombia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Congo (Brazzaville)'] != null) {
      congobrazzaville = new List<TimeSeri>();
      json['Congo (Brazzaville)'].forEach((v) {
        congobrazzaville.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Congo (Kinshasa)'] != null) {
      congokinshasa = new List<TimeSeri>();
      json['Congo (Kinshasa)'].forEach((v) {
        congokinshasa.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Costa Rica'] != null) {
      costa = new List<TimeSeri>();
      json['Costa Rica'].forEach((v) {
        costa.add(new TimeSeri.fromJson(v));
      });
    }
    if (json["Cote d'Ivoire"] != null) {
      cote = new List<TimeSeri>();
      json["Cote d'Ivoire"].forEach((v) {
        cote.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Croatia'] != null) {
      croatia = new List<TimeSeri>();
      json['Croatia'].forEach((v) {
        croatia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Diamond Princess'] != null) {
      diamond = new List<TimeSeri>();
      json['Diamond Princess'].forEach((v) {
        diamond.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Cuba'] != null) {
      cuba = new List<TimeSeri>();
      json['Cuba'].forEach((v) {
        cuba.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Cyprus'] != null) {
      cyprus = new List<TimeSeri>();
      json['Cyprus'].forEach((v) {
        cyprus.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Czechia'] != null) {
      czechia = new List<TimeSeri>();
      json['Czechia'].forEach((v) {
        czechia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Denmark'] != null) {
      denmark = new List<TimeSeri>();
      json['Denmark'].forEach((v) {
        denmark.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Djibouti'] != null) {
      djibouti = new List<TimeSeri>();
      json['Djibouti'].forEach((v) {
        djibouti.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Dominican Republic'] != null) {
      dominican = new List<TimeSeri>();
      json['Dominican Republic'].forEach((v) {
        dominican.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Ecuador'] != null) {
      ecuador = new List<TimeSeri>();
      json['Ecuador'].forEach((v) {
        ecuador.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Egypt'] != null) {
      egypt = new List<TimeSeri>();
      json['Egypt'].forEach((v) {
        egypt.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['El Salvador'] != null) {
      el = new List<TimeSeri>();
      json['El Salvador'].forEach((v) {
        el.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Equatorial Guinea'] != null) {
      equatorial = new List<TimeSeri>();
      json['Equatorial Guinea'].forEach((v) {
        equatorial.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Eritrea'] != null) {
      eritrea = new List<TimeSeri>();
      json['Eritrea'].forEach((v) {
        eritrea.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Estonia'] != null) {
      estonia = new List<TimeSeri>();
      json['Estonia'].forEach((v) {
        estonia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Eswatini'] != null) {
      eswatini = new List<TimeSeri>();
      json['Eswatini'].forEach((v) {
        eswatini.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Ethiopia'] != null) {
      ethiopia = new List<TimeSeri>();
      json['Ethiopia'].forEach((v) {
        ethiopia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Fiji'] != null) {
      fiji = new List<TimeSeri>();
      json['Fiji'].forEach((v) {
        fiji.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Finland'] != null) {
      finland = new List<TimeSeri>();
      json['Finland'].forEach((v) {
        finland.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['France'] != null) {
      france = new List<TimeSeri>();
      json['France'].forEach((v) {
        france.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Gabon'] != null) {
      gabon = new List<TimeSeri>();
      json['Gabon'].forEach((v) {
        gabon.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Gambia'] != null) {
      gambia = new List<TimeSeri>();
      json['Gambia'].forEach((v) {
        gambia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Georgia'] != null) {
      georgia = new List<TimeSeri>();
      json['Georgia'].forEach((v) {
        georgia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Germany'] != null) {
      germany = new List<TimeSeri>();
      json['Germany'].forEach((v) {
        germany.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Ghana'] != null) {
      ghana = new List<TimeSeri>();
      json['Ghana'].forEach((v) {
        ghana.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Greece'] != null) {
      greece = new List<TimeSeri>();
      json['Greece'].forEach((v) {
        greece.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Guatemala'] != null) {
      guatemala = new List<TimeSeri>();
      json['Guatemala'].forEach((v) {
        guatemala.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Guinea'] != null) {
      guinea = new List<TimeSeri>();
      json['Guinea'].forEach((v) {
        guinea.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Guyana'] != null) {
      guyana = new List<TimeSeri>();
      json['Guyana'].forEach((v) {
        guyana.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Haiti'] != null) {
      haiti = new List<TimeSeri>();
      json['Haiti'].forEach((v) {
        haiti.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Holy See'] != null) {
      holy = new List<TimeSeri>();
      json['Holy See'].forEach((v) {
        holy.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Honduras'] != null) {
      honduras = new List<TimeSeri>();
      json['Honduras'].forEach((v) {
        honduras.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Hungary'] != null) {
      hungary = new List<TimeSeri>();
      json['Hungary'].forEach((v) {
        hungary.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Iceland'] != null) {
      iceland = new List<TimeSeri>();
      json['Iceland'].forEach((v) {
        iceland.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['India'] != null) {
      india = new List<TimeSeri>();
      json['India'].forEach((v) {
        india.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Indonesia'] != null) {
      indonesia = new List<TimeSeri>();
      json['Indonesia'].forEach((v) {
        indonesia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Iran'] != null) {
      iran = new List<TimeSeri>();
      json['Iran'].forEach((v) {
        iran.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Iraq'] != null) {
      iraq = new List<TimeSeri>();
      json['Iraq'].forEach((v) {
        iraq.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Ireland'] != null) {
      ireland = new List<TimeSeri>();
      json['Ireland'].forEach((v) {
        ireland.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Israel'] != null) {
      israel = new List<TimeSeri>();
      json['Israel'].forEach((v) {
        israel.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Italy'] != null) {
      italy = new List<TimeSeri>();
      json['Italy'].forEach((v) {
        italy.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Jamaica'] != null) {
      jamaica = new List<TimeSeri>();
      json['Jamaica'].forEach((v) {
        jamaica.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Japan'] != null) {
      japan = new List<TimeSeri>();
      json['Japan'].forEach((v) {
        japan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Jordan'] != null) {
      jordan = new List<TimeSeri>();
      json['Jordan'].forEach((v) {
        jordan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Kazakhstan'] != null) {
      kazakhstan = new List<TimeSeri>();
      json['Kazakhstan'].forEach((v) {
        kazakhstan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Kenya'] != null) {
      kenya = new List<TimeSeri>();
      json['Kenya'].forEach((v) {
        kenya.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Korea, South'] != null) {
      korea = new List<TimeSeri>();
      json['Korea, South'].forEach((v) {
        korea.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Kuwait'] != null) {
      kuwait = new List<TimeSeri>();
      json['Kuwait'].forEach((v) {
        kuwait.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Kyrgyzstan'] != null) {
      kyrgyzstan = new List<TimeSeri>();
      json['Kyrgyzstan'].forEach((v) {
        kyrgyzstan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Latvia'] != null) {
      latvia = new List<TimeSeri>();
      json['Latvia'].forEach((v) {
        latvia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Lebanon'] != null) {
      lebanon = new List<TimeSeri>();
      json['Lebanon'].forEach((v) {
        lebanon.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Liberia'] != null) {
      liberia = new List<TimeSeri>();
      json['Liberia'].forEach((v) {
        liberia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Liechtenstein'] != null) {
      liechtenstein = new List<TimeSeri>();
      json['Liechtenstein'].forEach((v) {
        liechtenstein.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Lithuania'] != null) {
      lithuania = new List<TimeSeri>();
      json['Lithuania'].forEach((v) {
        lithuania.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Luxembourg'] != null) {
      luxembourg = new List<TimeSeri>();
      json['Luxembourg'].forEach((v) {
        luxembourg.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Madagascar'] != null) {
      madagascar = new List<TimeSeri>();
      json['Madagascar'].forEach((v) {
        madagascar.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Malaysia'] != null) {
      malaysia = new List<TimeSeri>();
      json['Malaysia'].forEach((v) {
        malaysia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Maldives'] != null) {
      maldives = new List<TimeSeri>();
      json['Maldives'].forEach((v) {
        maldives.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Malta'] != null) {
      malta = new List<TimeSeri>();
      json['Malta'].forEach((v) {
        malta.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Mauritania'] != null) {
      mauritania = new List<TimeSeri>();
      json['Mauritania'].forEach((v) {
        mauritania.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Mauritius'] != null) {
      mauritius = new List<TimeSeri>();
      json['Mauritius'].forEach((v) {
        mauritius.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Mexico'] != null) {
      mexico = new List<TimeSeri>();
      json['Mexico'].forEach((v) {
        mexico.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Moldova'] != null) {
      moldova = new List<TimeSeri>();
      json['Moldova'].forEach((v) {
        moldova.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Monaco'] != null) {
      monaco = new List<TimeSeri>();
      json['Monaco'].forEach((v) {
        monaco.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Mongolia'] != null) {
      mongolia = new List<TimeSeri>();
      json['Mongolia'].forEach((v) {
        mongolia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Montenegro'] != null) {
      montenegro = new List<TimeSeri>();
      json['Montenegro'].forEach((v) {
        montenegro.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Morocco'] != null) {
      morocco = new List<TimeSeri>();
      json['Morocco'].forEach((v) {
        morocco.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Namibia'] != null) {
      namibia = new List<TimeSeri>();
      json['Namibia'].forEach((v) {
        namibia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Nepal'] != null) {
      nepal = new List<TimeSeri>();
      json['Nepal'].forEach((v) {
        nepal.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Netherlands'] != null) {
      netherlands = new List<TimeSeri>();
      json['Netherlands'].forEach((v) {
        netherlands.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['New Zealand'] != null) {
      newzealand = new List<TimeSeri>();
      json['New Zealand'].forEach((v) {
        newzealand.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Nicaragua'] != null) {
      nicaragua = new List<TimeSeri>();
      json['Nicaragua'].forEach((v) {
        nicaragua.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Niger'] != null) {
      niger = new List<TimeSeri>();
      json['Niger'].forEach((v) {
        niger.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Nigeria'] != null) {
      nigeria = new List<TimeSeri>();
      json['Nigeria'].forEach((v) {
        nigeria.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['North Macedonia'] != null) {
      north = new List<TimeSeri>();
      json['North Macedonia'].forEach((v) {
        north.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Norway'] != null) {
      norway = new List<TimeSeri>();
      json['Norway'].forEach((v) {
        norway.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Oman'] != null) {
      oman = new List<TimeSeri>();
      json['Oman'].forEach((v) {
        oman.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Pakistan'] != null) {
      pakistan = new List<TimeSeri>();
      json['Pakistan'].forEach((v) {
        pakistan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Panama'] != null) {
      panama = new List<TimeSeri>();
      json['Panama'].forEach((v) {
        panama.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Papua New Guinea'] != null) {
      papua = new List<TimeSeri>();
      json['Papua New Guinea'].forEach((v) {
        papua.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Paraguay'] != null) {
      paraguay = new List<TimeSeri>();
      json['Paraguay'].forEach((v) {
        paraguay.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Peru'] != null) {
      peru = new List<TimeSeri>();
      json['Peru'].forEach((v) {
        peru.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Philippines'] != null) {
      philippines = new List<TimeSeri>();
      json['Philippines'].forEach((v) {
        philippines.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Poland'] != null) {
      poland = new List<TimeSeri>();
      json['Poland'].forEach((v) {
        poland.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Portugal'] != null) {
      portugal = new List<TimeSeri>();
      json['Portugal'].forEach((v) {
        portugal.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Qatar'] != null) {
      qatar = new List<TimeSeri>();
      json['Qatar'].forEach((v) {
        qatar.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Romania'] != null) {
      romania = new List<TimeSeri>();
      json['Romania'].forEach((v) {
        romania.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Russia'] != null) {
      russia = new List<TimeSeri>();
      json['Russia'].forEach((v) {
        russia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Rwanda'] != null) {
      rwanda = new List<TimeSeri>();
      json['Rwanda'].forEach((v) {
        rwanda.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Saint Lucia'] != null) {
      saint = new List<TimeSeri>();
      json['Saint Lucia'].forEach((v) {
        saint.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Saint Vincent and the Grenadines'] != null) {
      saint = new List<TimeSeri>();
      json['Saint Vincent and the Grenadines'].forEach((v) {
        saint.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['San Marino'] != null) {
      san = new List<TimeSeri>();
      json['San Marino'].forEach((v) {
        san.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Saudi Arabia'] != null) {
      saudi = new List<TimeSeri>();
      json['Saudi Arabia'].forEach((v) {
        saudi.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Senegal'] != null) {
      senegal = new List<TimeSeri>();
      json['Senegal'].forEach((v) {
        senegal.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Serbia'] != null) {
      serbia = new List<TimeSeri>();
      json['Serbia'].forEach((v) {
        serbia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Seychelles'] != null) {
      seychelles = new List<TimeSeri>();
      json['Seychelles'].forEach((v) {
        seychelles.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Singapore'] != null) {
      singapore = new List<TimeSeri>();
      json['Singapore'].forEach((v) {
        singapore.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Slovakia'] != null) {
      slovakia = new List<TimeSeri>();
      json['Slovakia'].forEach((v) {
        slovakia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Slovenia'] != null) {
      slovenia = new List<TimeSeri>();
      json['Slovenia'].forEach((v) {
        slovenia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Somalia'] != null) {
      somalia = new List<TimeSeri>();
      json['Somalia'].forEach((v) {
        somalia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['South Africa'] != null) {
      south = new List<TimeSeri>();
      json['South Africa'].forEach((v) {
        south.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Spain'] != null) {
      spain = new List<TimeSeri>();
      json['Spain'].forEach((v) {
        spain.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Sri Lanka'] != null) {
      sri = new List<TimeSeri>();
      json['Sri Lanka'].forEach((v) {
        sri.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Sudan'] != null) {
      sudan = new List<TimeSeri>();
      json['Sudan'].forEach((v) {
        sudan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Suriname'] != null) {
      suriname = new List<TimeSeri>();
      json['Suriname'].forEach((v) {
        suriname.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Sweden'] != null) {
      sweden = new List<TimeSeri>();
      json['Sweden'].forEach((v) {
        sweden.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Switzerland'] != null) {
      switzerland = new List<TimeSeri>();
      json['Switzerland'].forEach((v) {
        switzerland.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Taiwan*'] != null) {
      taiwan = new List<TimeSeri>();
      json['Taiwan*'].forEach((v) {
        taiwan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Tanzania'] != null) {
      tanzania = new List<TimeSeri>();
      json['Tanzania'].forEach((v) {
        tanzania.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Thailand'] != null) {
      thailand = new List<TimeSeri>();
      json['Thailand'].forEach((v) {
        thailand.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Togo'] != null) {
      togo = new List<TimeSeri>();
      json['Togo'].forEach((v) {
        togo.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Trinidad and Tobago'] != null) {
      trinidad = new List<TimeSeri>();
      json['Trinidad and Tobago'].forEach((v) {
        trinidad.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Tunisia'] != null) {
      tunisia = new List<TimeSeri>();
      json['Tunisia'].forEach((v) {
        tunisia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Turkey'] != null) {
      turkey = new List<TimeSeri>();
      json['Turkey'].forEach((v) {
        turkey.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Uganda'] != null) {
      uganda = new List<TimeSeri>();
      json['Uganda'].forEach((v) {
        uganda.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Ukraine'] != null) {
      ukraine = new List<TimeSeri>();
      json['Ukraine'].forEach((v) {
        ukraine.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['United Arab Emirates'] != null) {
      unitedarab = new List<TimeSeri>();
      json['United Arab Emirates'].forEach((v) {
        unitedarab.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['United Kingdom'] != null) {
      unitedkingdom = new List<TimeSeri>();
      json['United Kingdom'].forEach((v) {
        unitedkingdom.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Uruguay'] != null) {
      uruguay = new List<TimeSeri>();
      json['Uruguay'].forEach((v) {
        uruguay.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['US'] != null) {
      us = new List<TimeSeri>();
      json['US'].forEach((v) {
        us.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Uzbekistan'] != null) {
      uzbekistan = new List<TimeSeri>();
      json['Uzbekistan'].forEach((v) {
        uzbekistan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Venezuela'] != null) {
      venezuela = new List<TimeSeri>();
      json['Venezuela'].forEach((v) {
        venezuela.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Vietnam'] != null) {
      vietnam = new List<TimeSeri>();
      json['Vietnam'].forEach((v) {
        vietnam.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Zambia'] != null) {
      zambia = new List<TimeSeri>();
      json['Zambia'].forEach((v) {
        zambia.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Zimbabwe'] != null) {
      zimbabwe = new List<TimeSeri>();
      json['Zimbabwe'].forEach((v) {
        zimbabwe.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Dominica'] != null) {
      dominica = new List<TimeSeri>();
      json['Dominica'].forEach((v) {
        dominica.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Grenada'] != null) {
      grenada = new List<TimeSeri>();
      json['Grenada'].forEach((v) {
        grenada.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Mozambique'] != null) {
      mozambique = new List<TimeSeri>();
      json['Mozambique'].forEach((v) {
        mozambique.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Syria'] != null) {
      syria = new List<TimeSeri>();
      json['Syria'].forEach((v) {
        syria.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Timor-Leste'] != null) {
      timorleste = new List<TimeSeri>();
      json['Timor-Leste'].forEach((v) {
        timorleste.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Belize'] != null) {
      belize = new List<TimeSeri>();
      json['Belize'].forEach((v) {
        belize.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Laos'] != null) {
      laos = new List<TimeSeri>();
      json['Laos'].forEach((v) {
        laos.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Libya'] != null) {
      libya = new List<TimeSeri>();
      json['Libya'].forEach((v) {
        libya.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['West Bank and Gaza'] != null) {
      west = new List<TimeSeri>();
      json['West Bank and Gaza'].forEach((v) {
        west.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Guinea-Bissau'] != null) {
      guineabissau = new List<TimeSeri>();
      json['Guinea-Bissau'].forEach((v) {
        guineabissau.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Mali'] != null) {
      mali = new List<TimeSeri>();
      json['Mali'].forEach((v) {
        mali.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Saint Kitts and Nevis'] != null) {
      saint = new List<TimeSeri>();
      json['Saint Kitts and Nevis'].forEach((v) {
        saint.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Kosovo'] != null) {
      kosovo = new List<TimeSeri>();
      json['Kosovo'].forEach((v) {
        kosovo.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Burma'] != null) {
      burma = new List<TimeSeri>();
      json['Burma'].forEach((v) {
        burma.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['MS Zaandam'] != null) {
      ms = new List<TimeSeri>();
      json['MS Zaandam'].forEach((v) {
        ms.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Botswana'] != null) {
      botswana = new List<TimeSeri>();
      json['Botswana'].forEach((v) {
        botswana.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Burundi'] != null) {
      burundi = new List<TimeSeri>();
      json['Burundi'].forEach((v) {
        burundi.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Sierra Leone'] != null) {
      sierra = new List<TimeSeri>();
      json['Sierra Leone'].forEach((v) {
        sierra.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Malawi'] != null) {
      malawi = new List<TimeSeri>();
      json['Malawi'].forEach((v) {
        malawi.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['South Sudan'] != null) {
      south = new List<TimeSeri>();
      json['South Sudan'].forEach((v) {
        south.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Western Sahara'] != null) {
      western = new List<TimeSeri>();
      json['Western Sahara'].forEach((v) {
        western.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Sao Tome and Principe'] != null) {
      sao = new List<TimeSeri>();
      json['Sao Tome and Principe'].forEach((v) {
        sao.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Yemen'] != null) {
      yemen = new List<TimeSeri>();
      json['Yemen'].forEach((v) {
        yemen.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Comoros'] != null) {
      comoros = new List<TimeSeri>();
      json['Comoros'].forEach((v) {
        comoros.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Tajikistan'] != null) {
      tajikistan = new List<TimeSeri>();
      json['Tajikistan'].forEach((v) {
        tajikistan.add(new TimeSeri.fromJson(v));
      });
    }
    if (json['Lesotho'] != null) {
      lesotho = new List<TimeSeri>();
      json['Lesotho'].forEach((v) {
        lesotho.add(new TimeSeri.fromJson(v));
      });
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.afghanistan != null) {
      data['Afghanistan'] = this.afghanistan.map((v) => v.toJson()).toList();
    }
    if (this.albania != null) {
      data['Albania'] = this.albania.map((v) => v.toJson()).toList();
    }
    if (this.algeria != null) {
      data['Algeria'] = this.algeria.map((v) => v.toJson()).toList();
    }
    if (this.andorra != null) {
      data['Andorra'] = this.andorra.map((v) => v.toJson()).toList();
    }
    if (this.angola != null) {
      data['Angola'] = this.angola.map((v) => v.toJson()).toList();
    }
    if (this.antigua != null) {
      data['Antigua and Barbuda'] =
          this.antigua.map((v) => v.toJson()).toList();
    }
    if (this.argentina != null) {
      data['Argentina'] = this.argentina.map((v) => v.toJson()).toList();
    }
    if (this.armenia != null) {
      data['Armenia'] = this.armenia.map((v) => v.toJson()).toList();
    }
    if (this.australia != null) {
      data['Australia'] = this.australia.map((v) => v.toJson()).toList();
    }
    if (this.austria != null) {
      data['Austria'] = this.austria.map((v) => v.toJson()).toList();
    }
    if (this.azerbaijan != null) {
      data['Azerbaijan'] = this.azerbaijan.map((v) => v.toJson()).toList();
    }
    if (this.bahamas != null) {
      data['Bahamas'] = this.bahamas.map((v) => v.toJson()).toList();
    }
    if (this.bahrain != null) {
      data['Bahrain'] = this.bahrain.map((v) => v.toJson()).toList();
    }
    if (this.bangladesh != null) {
      data['Bangladesh'] = this.bangladesh.map((v) => v.toJson()).toList();
    }
    if (this.barbados != null) {
      data['Barbados'] = this.barbados.map((v) => v.toJson()).toList();
    }
    if (this.belarus != null) {
      data['Belarus'] = this.belarus.map((v) => v.toJson()).toList();
    }
    if (this.belgium != null) {
      data['Belgium'] = this.belgium.map((v) => v.toJson()).toList();
    }
    if (this.benin != null) {
      data['Benin'] = this.benin.map((v) => v.toJson()).toList();
    }
    if (this.bhutan != null) {
      data['Bhutan'] = this.bhutan.map((v) => v.toJson()).toList();
    }
    if (this.bolivia != null) {
      data['Bolivia'] = this.bolivia.map((v) => v.toJson()).toList();
    }
    if (this.bosnia != null) {
      data['Bosnia and Herzegovina'] =
          this.bosnia.map((v) => v.toJson()).toList();
    }
    if (this.brazil != null) {
      data['Brazil'] = this.brazil.map((v) => v.toJson()).toList();
    }
    if (this.brunei != null) {
      data['Brunei'] = this.brunei.map((v) => v.toJson()).toList();
    }
    if (this.bulgaria != null) {
      data['Bulgaria'] = this.bulgaria.map((v) => v.toJson()).toList();
    }
    if (this.burkina != null) {
      data['Burkina Faso'] = this.burkina.map((v) => v.toJson()).toList();
    }
    if (this.cabo != null) {
      data['Cabo Verde'] = this.cabo.map((v) => v.toJson()).toList();
    }
    if (this.cambodia != null) {
      data['Cambodia'] = this.cambodia.map((v) => v.toJson()).toList();
    }
    if (this.cameroon != null) {
      data['Cameroon'] = this.cameroon.map((v) => v.toJson()).toList();
    }
    if (this.canada != null) {
      data['Canada'] = this.canada.map((v) => v.toJson()).toList();
    }
    if (this.central != null) {
      data['Central African Republic'] =
          this.central.map((v) => v.toJson()).toList();
    }
    if (this.chad != null) {
      data['Chad'] = this.chad.map((v) => v.toJson()).toList();
    }
    if (this.chile != null) {
      data['Chile'] = this.chile.map((v) => v.toJson()).toList();
    }
    if (this.china != null) {
      data['China'] = this.china.map((v) => v.toJson()).toList();
    }
    if (this.colombia != null) {
      data['Colombia'] = this.colombia.map((v) => v.toJson()).toList();
    }
    if (this.congobrazzaville != null) {
      data['Congo (Brazzaville)'] =
          this.congobrazzaville.map((v) => v.toJson()).toList();
    }
    if (this.congokinshasa != null) {
      data['Congo (Kinshasa)'] =
          this.congokinshasa.map((v) => v.toJson()).toList();
    }
    if (this.costa != null) {
      data['Costa Rica'] = this.costa.map((v) => v.toJson()).toList();
    }
    if (this.cote != null) {
      data["Cote d'Ivoire"] = this.cote.map((v) => v.toJson()).toList();
    }
    if (this.croatia != null) {
      data['Croatia'] = this.croatia.map((v) => v.toJson()).toList();
    }
    if (this.diamond != null) {
      data['Diamond Princess'] = this.diamond.map((v) => v.toJson()).toList();
    }
    if (this.cuba != null) {
      data['Cuba'] = this.cuba.map((v) => v.toJson()).toList();
    }
    if (this.cyprus != null) {
      data['Cyprus'] = this.cyprus.map((v) => v.toJson()).toList();
    }
    if (this.czechia != null) {
      data['Czechia'] = this.czechia.map((v) => v.toJson()).toList();
    }
    if (this.denmark != null) {
      data['Denmark'] = this.denmark.map((v) => v.toJson()).toList();
    }
    if (this.djibouti != null) {
      data['Djibouti'] = this.djibouti.map((v) => v.toJson()).toList();
    }
    if (this.dominican != null) {
      data['Dominican Republic'] =
          this.dominican.map((v) => v.toJson()).toList();
    }
    if (this.ecuador != null) {
      data['Ecuador'] = this.ecuador.map((v) => v.toJson()).toList();
    }
    if (this.egypt != null) {
      data['Egypt'] = this.egypt.map((v) => v.toJson()).toList();
    }
    if (this.el != null) {
      data['El Salvador'] = this.el.map((v) => v.toJson()).toList();
    }
    if (this.equatorial != null) {
      data['Equatorial Guinea'] =
          this.equatorial.map((v) => v.toJson()).toList();
    }
    if (this.eritrea != null) {
      data['Eritrea'] = this.eritrea.map((v) => v.toJson()).toList();
    }
    if (this.estonia != null) {
      data['Estonia'] = this.estonia.map((v) => v.toJson()).toList();
    }
    if (this.eswatini != null) {
      data['Eswatini'] = this.eswatini.map((v) => v.toJson()).toList();
    }
    if (this.ethiopia != null) {
      data['Ethiopia'] = this.ethiopia.map((v) => v.toJson()).toList();
    }
    if (this.fiji != null) {
      data['Fiji'] = this.fiji.map((v) => v.toJson()).toList();
    }
    if (this.finland != null) {
      data['Finland'] = this.finland.map((v) => v.toJson()).toList();
    }
    if (this.france != null) {
      data['France'] = this.france.map((v) => v.toJson()).toList();
    }
    if (this.gabon != null) {
      data['Gabon'] = this.gabon.map((v) => v.toJson()).toList();
    }
    if (this.gambia != null) {
      data['Gambia'] = this.gambia.map((v) => v.toJson()).toList();
    }
    if (this.georgia != null) {
      data['Georgia'] = this.georgia.map((v) => v.toJson()).toList();
    }
    if (this.germany != null) {
      data['Germany'] = this.germany.map((v) => v.toJson()).toList();
    }
    if (this.ghana != null) {
      data['Ghana'] = this.ghana.map((v) => v.toJson()).toList();
    }
    if (this.greece != null) {
      data['Greece'] = this.greece.map((v) => v.toJson()).toList();
    }
    if (this.guatemala != null) {
      data['Guatemala'] = this.guatemala.map((v) => v.toJson()).toList();
    }
    if (this.guinea != null) {
      data['Guinea'] = this.guinea.map((v) => v.toJson()).toList();
    }
    if (this.guyana != null) {
      data['Guyana'] = this.guyana.map((v) => v.toJson()).toList();
    }
    if (this.haiti != null) {
      data['Haiti'] = this.haiti.map((v) => v.toJson()).toList();
    }
    if (this.holy != null) {
      data['Holy See'] = this.holy.map((v) => v.toJson()).toList();
    }
    if (this.honduras != null) {
      data['Honduras'] = this.honduras.map((v) => v.toJson()).toList();
    }
    if (this.hungary != null) {
      data['Hungary'] = this.hungary.map((v) => v.toJson()).toList();
    }
    if (this.iceland != null) {
      data['Iceland'] = this.iceland.map((v) => v.toJson()).toList();
    }
    if (this.india != null) {
      data['India'] = this.india.map((v) => v.toJson()).toList();
    }
    if (this.indonesia != null) {
      data['Indonesia'] = this.indonesia.map((v) => v.toJson()).toList();
    }
    if (this.iran != null) {
      data['Iran'] = this.iran.map((v) => v.toJson()).toList();
    }
    if (this.iraq != null) {
      data['Iraq'] = this.iraq.map((v) => v.toJson()).toList();
    }
    if (this.ireland != null) {
      data['Ireland'] = this.ireland.map((v) => v.toJson()).toList();
    }
    if (this.israel != null) {
      data['Israel'] = this.israel.map((v) => v.toJson()).toList();
    }
    if (this.italy != null) {
      data['Italy'] = this.italy.map((v) => v.toJson()).toList();
    }
    if (this.jamaica != null) {
      data['Jamaica'] = this.jamaica.map((v) => v.toJson()).toList();
    }
    if (this.japan != null) {
      data['Japan'] = this.japan.map((v) => v.toJson()).toList();
    }
    if (this.jordan != null) {
      data['Jordan'] = this.jordan.map((v) => v.toJson()).toList();
    }
    if (this.kazakhstan != null) {
      data['Kazakhstan'] = this.kazakhstan.map((v) => v.toJson()).toList();
    }
    if (this.kenya != null) {
      data['Kenya'] = this.kenya.map((v) => v.toJson()).toList();
    }
    if (this.korea != null) {
      data['Korea, South'] = this.korea.map((v) => v.toJson()).toList();
    }
    if (this.kuwait != null) {
      data['Kuwait'] = this.kuwait.map((v) => v.toJson()).toList();
    }
    if (this.kyrgyzstan != null) {
      data['Kyrgyzstan'] = this.kyrgyzstan.map((v) => v.toJson()).toList();
    }
    if (this.latvia != null) {
      data['Latvia'] = this.latvia.map((v) => v.toJson()).toList();
    }
    if (this.lebanon != null) {
      data['Lebanon'] = this.lebanon.map((v) => v.toJson()).toList();
    }
    if (this.liberia != null) {
      data['Liberia'] = this.liberia.map((v) => v.toJson()).toList();
    }
    if (this.liechtenstein != null) {
      data['Liechtenstein'] =
          this.liechtenstein.map((v) => v.toJson()).toList();
    }
    if (this.lithuania != null) {
      data['Lithuania'] = this.lithuania.map((v) => v.toJson()).toList();
    }
    if (this.luxembourg != null) {
      data['Luxembourg'] = this.luxembourg.map((v) => v.toJson()).toList();
    }
    if (this.madagascar != null) {
      data['Madagascar'] = this.madagascar.map((v) => v.toJson()).toList();
    }
    if (this.malaysia != null) {
      data['Malaysia'] = this.malaysia.map((v) => v.toJson()).toList();
    }
    if (this.maldives != null) {
      data['Maldives'] = this.maldives.map((v) => v.toJson()).toList();
    }
    if (this.malta != null) {
      data['Malta'] = this.malta.map((v) => v.toJson()).toList();
    }
    if (this.mauritania != null) {
      data['Mauritania'] = this.mauritania.map((v) => v.toJson()).toList();
    }
    if (this.mauritius != null) {
      data['Mauritius'] = this.mauritius.map((v) => v.toJson()).toList();
    }
    if (this.mexico != null) {
      data['Mexico'] = this.mexico.map((v) => v.toJson()).toList();
    }
    if (this.moldova != null) {
      data['Moldova'] = this.moldova.map((v) => v.toJson()).toList();
    }
    if (this.monaco != null) {
      data['Monaco'] = this.monaco.map((v) => v.toJson()).toList();
    }
    if (this.mongolia != null) {
      data['Mongolia'] = this.mongolia.map((v) => v.toJson()).toList();
    }
    if (this.montenegro != null) {
      data['Montenegro'] = this.montenegro.map((v) => v.toJson()).toList();
    }
    if (this.morocco != null) {
      data['Morocco'] = this.morocco.map((v) => v.toJson()).toList();
    }
    if (this.namibia != null) {
      data['Namibia'] = this.namibia.map((v) => v.toJson()).toList();
    }
    if (this.nepal != null) {
      data['Nepal'] = this.nepal.map((v) => v.toJson()).toList();
    }
    if (this.netherlands != null) {
      data['Netherlands'] = this.netherlands.map((v) => v.toJson()).toList();
    }
    if (this.newzealand != null) {
      data['New Zealand'] = this.newzealand.map((v) => v.toJson()).toList();
    }
    if (this.nicaragua != null) {
      data['Nicaragua'] = this.nicaragua.map((v) => v.toJson()).toList();
    }
    if (this.niger != null) {
      data['Niger'] = this.niger.map((v) => v.toJson()).toList();
    }
    if (this.nigeria != null) {
      data['Nigeria'] = this.nigeria.map((v) => v.toJson()).toList();
    }
    if (this.north != null) {
      data['North Macedonia'] = this.north.map((v) => v.toJson()).toList();
    }
    if (this.norway != null) {
      data['Norway'] = this.norway.map((v) => v.toJson()).toList();
    }
    if (this.oman != null) {
      data['Oman'] = this.oman.map((v) => v.toJson()).toList();
    }
    if (this.pakistan != null) {
      data['Pakistan'] = this.pakistan.map((v) => v.toJson()).toList();
    }
    if (this.panama != null) {
      data['Panama'] = this.panama.map((v) => v.toJson()).toList();
    }
    if (this.papua != null) {
      data['Papua New Guinea'] = this.papua.map((v) => v.toJson()).toList();
    }
    if (this.paraguay != null) {
      data['Paraguay'] = this.paraguay.map((v) => v.toJson()).toList();
    }
    if (this.peru != null) {
      data['Peru'] = this.peru.map((v) => v.toJson()).toList();
    }
    if (this.philippines != null) {
      data['Philippines'] = this.philippines.map((v) => v.toJson()).toList();
    }
    if (this.poland != null) {
      data['Poland'] = this.poland.map((v) => v.toJson()).toList();
    }
    if (this.portugal != null) {
      data['Portugal'] = this.portugal.map((v) => v.toJson()).toList();
    }
    if (this.qatar != null) {
      data['Qatar'] = this.qatar.map((v) => v.toJson()).toList();
    }
    if (this.romania != null) {
      data['Romania'] = this.romania.map((v) => v.toJson()).toList();
    }
    if (this.russia != null) {
      data['Russia'] = this.russia.map((v) => v.toJson()).toList();
    }
    if (this.rwanda != null) {
      data['Rwanda'] = this.rwanda.map((v) => v.toJson()).toList();
    }
    if (this.saint != null) {
      data['Saint Lucia'] = this.saint.map((v) => v.toJson()).toList();
    }
    if (this.saint != null) {
      data['Saint Vincent and the Grenadines'] =
          this.saint.map((v) => v.toJson()).toList();
    }
    if (this.san != null) {
      data['San Marino'] = this.san.map((v) => v.toJson()).toList();
    }
    if (this.saudi != null) {
      data['Saudi Arabia'] = this.saudi.map((v) => v.toJson()).toList();
    }
    if (this.senegal != null) {
      data['Senegal'] = this.senegal.map((v) => v.toJson()).toList();
    }
    if (this.serbia != null) {
      data['Serbia'] = this.serbia.map((v) => v.toJson()).toList();
    }
    if (this.seychelles != null) {
      data['Seychelles'] = this.seychelles.map((v) => v.toJson()).toList();
    }
    if (this.singapore != null) {
      data['Singapore'] = this.singapore.map((v) => v.toJson()).toList();
    }
    if (this.slovakia != null) {
      data['Slovakia'] = this.slovakia.map((v) => v.toJson()).toList();
    }
    if (this.slovenia != null) {
      data['Slovenia'] = this.slovenia.map((v) => v.toJson()).toList();
    }
    if (this.somalia != null) {
      data['Somalia'] = this.somalia.map((v) => v.toJson()).toList();
    }
    if (this.south != null) {
      data['South Africa'] = this.south.map((v) => v.toJson()).toList();
    }
    if (this.spain != null) {
      data['Spain'] = this.spain.map((v) => v.toJson()).toList();
    }
    if (this.sri != null) {
      data['Sri Lanka'] = this.sri.map((v) => v.toJson()).toList();
    }
    if (this.sudan != null) {
      data['Sudan'] = this.sudan.map((v) => v.toJson()).toList();
    }
    if (this.suriname != null) {
      data['Suriname'] = this.suriname.map((v) => v.toJson()).toList();
    }
    if (this.sweden != null) {
      data['Sweden'] = this.sweden.map((v) => v.toJson()).toList();
    }
    if (this.switzerland != null) {
      data['Switzerland'] = this.switzerland.map((v) => v.toJson()).toList();
    }
    if (this.taiwan != null) {
      data['Taiwan*'] = this.taiwan.map((v) => v.toJson()).toList();
    }
    if (this.tanzania != null) {
      data['Tanzania'] = this.tanzania.map((v) => v.toJson()).toList();
    }
    if (this.thailand != null) {
      data['Thailand'] = this.thailand.map((v) => v.toJson()).toList();
    }
    if (this.togo != null) {
      data['Togo'] = this.togo.map((v) => v.toJson()).toList();
    }
    if (this.trinidad != null) {
      data['Trinidad and Tobago'] =
          this.trinidad.map((v) => v.toJson()).toList();
    }
    if (this.tunisia != null) {
      data['Tunisia'] = this.tunisia.map((v) => v.toJson()).toList();
    }
    if (this.turkey != null) {
      data['Turkey'] = this.turkey.map((v) => v.toJson()).toList();
    }
    if (this.uganda != null) {
      data['Uganda'] = this.uganda.map((v) => v.toJson()).toList();
    }
    if (this.ukraine != null) {
      data['Ukraine'] = this.ukraine.map((v) => v.toJson()).toList();
    }
    if (this.unitedarab != null) {
      data['United Arab Emirates'] =
          this.unitedarab.map((v) => v.toJson()).toList();
    }
    if (this.unitedkingdom != null) {
      data['United Kingdom'] =
          this.unitedkingdom.map((v) => v.toJson()).toList();
    }
    if (this.uruguay != null) {
      data['Uruguay'] = this.uruguay.map((v) => v.toJson()).toList();
    }
    if (this.us != null) {
      data['US'] = this.us.map((v) => v.toJson()).toList();
    }
    if (this.uzbekistan != null) {
      data['Uzbekistan'] = this.uzbekistan.map((v) => v.toJson()).toList();
    }
    if (this.venezuela != null) {
      data['Venezuela'] = this.venezuela.map((v) => v.toJson()).toList();
    }
    if (this.vietnam != null) {
      data['Vietnam'] = this.vietnam.map((v) => v.toJson()).toList();
    }
    if (this.zambia != null) {
      data['Zambia'] = this.zambia.map((v) => v.toJson()).toList();
    }
    if (this.zimbabwe != null) {
      data['Zimbabwe'] = this.zimbabwe.map((v) => v.toJson()).toList();
    }
    if (this.dominica != null) {
      data['Dominica'] = this.dominica.map((v) => v.toJson()).toList();
    }
    if (this.grenada != null) {
      data['Grenada'] = this.grenada.map((v) => v.toJson()).toList();
    }
    if (this.mozambique != null) {
      data['Mozambique'] = this.mozambique.map((v) => v.toJson()).toList();
    }
    if (this.syria != null) {
      data['Syria'] = this.syria.map((v) => v.toJson()).toList();
    }
    if (this.timorleste != null) {
      data['Timor-Leste'] = this.timorleste.map((v) => v.toJson()).toList();
    }
    if (this.belize != null) {
      data['Belize'] = this.belize.map((v) => v.toJson()).toList();
    }
    if (this.laos != null) {
      data['Laos'] = this.laos.map((v) => v.toJson()).toList();
    }
    if (this.libya != null) {
      data['Libya'] = this.libya.map((v) => v.toJson()).toList();
    }
    if (this.west != null) {
      data['West Bank and Gaza'] = this.west.map((v) => v.toJson()).toList();
    }
    if (this.guineabissau != null) {
      data['Guinea-Bissau'] = this.guineabissau.map((v) => v.toJson()).toList();
    }
    if (this.mali != null) {
      data['Mali'] = this.mali.map((v) => v.toJson()).toList();
    }
    if (this.saint != null) {
      data['Saint Kitts and Nevis'] =
          this.saint.map((v) => v.toJson()).toList();
    }
    if (this.kosovo != null) {
      data['Kosovo'] = this.kosovo.map((v) => v.toJson()).toList();
    }
    if (this.burma != null) {
      data['Burma'] = this.burma.map((v) => v.toJson()).toList();
    }
    if (this.ms != null) {
      data['MS Zaandam'] = this.ms.map((v) => v.toJson()).toList();
    }
    if (this.botswana != null) {
      data['Botswana'] = this.botswana.map((v) => v.toJson()).toList();
    }
    if (this.burundi != null) {
      data['Burundi'] = this.burundi.map((v) => v.toJson()).toList();
    }
    if (this.sierra != null) {
      data['Sierra Leone'] = this.sierra.map((v) => v.toJson()).toList();
    }
    if (this.malawi != null) {
      data['Malawi'] = this.malawi.map((v) => v.toJson()).toList();
    }
    if (this.south != null) {
      data['South Sudan'] = this.south.map((v) => v.toJson()).toList();
    }
    if (this.western != null) {
      data['Western Sahara'] = this.western.map((v) => v.toJson()).toList();
    }
    if (this.sao != null) {
      data['Sao Tome and Principe'] = this.sao.map((v) => v.toJson()).toList();
    }
    if (this.yemen != null) {
      data['Yemen'] = this.yemen.map((v) => v.toJson()).toList();
    }
    if (this.comoros != null) {
      data['Comoros'] = this.comoros.map((v) => v.toJson()).toList();
    }
    if (this.tajikistan != null) {
      data['Tajikistan'] = this.tajikistan.map((v) => v.toJson()).toList();
    }
    if (this.lesotho != null) {
      data['Lesotho'] = this.lesotho.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
