import 'package:flutter/material.dart';
import 'mainhome.dart';
import 'constants.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter/gestures.dart';
void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: MainHome());
  }
}

/*Future<Autogenerated> fetchTimeSeri() async {
    
    var response = await http.get("https://pomber.github.io/covid19/timeseries.json");
    if (response.statusCode == 200) 
      {
          var responseJson = json.decode(response.body);
          return Autogenerated.fromJson(responseJson);
      }
      else {
    throw Exception('${response.statusCode}');
    
  }
  }
  Future<List<TimeSeri>> fetch() async {
    final response =
      await http.get('https://pomber.github.io/covid19/timeseries.json');
  
    if (response.statusCode == 200) {
     final jsonObject = json.decode(response.body) as Map;
     final object = jsonObject['Vietnam'];
      return object
        .map<TimeSeri>((json) => TimeSeri.fromJson(json))
        .toList(growable: false);
    
  } else {
    throw Exception('${response.statusCode}');
    
  }
}*/
/*Future<Map<String, dynamic>> fetc() async {
    final response =
      await http.get('https://pomber.github.io/covid19/timeseries.json');
  
    if (response.statusCode == 200) {
     final jsonObject = json.decode(response.body);
      return jsonObject;
    
  } else {
    throw Exception('${response.statusCode}');
    
  }
}*/
class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  
  @override
  void initState() {
    super.initState();
  }
       @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center( child: Container(color: Colors.red, child: RichText(
          text: TextSpan(
            children: [
              TextSpan(
                text: "HAHAHA",
              ),
              TextSpan(
              
                text: "huhu",
                recognizer: TapGestureRecognizer()
                  ..onTap = () async {
                    final url = 'https://github.com/flutter/gallery/';
                    if (await canLaunch(url)) {
                      await launch(
                        url,
                        forceSafariVC: false,
                      );
                    }
                  },
              ),
              TextSpan(
                text: "kk",
              ),
            ],
          ),
    ))));
    }
  /*@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("${vietnam['2020-1-22']['confirmed']}"),
        ),
        body: ListView.builder(
        itemCount: kkk.length,
        itemBuilder: (context, index) {
          var project = kkk[index];
          return Text(project);
                 
        })
       /* Center(
          child: FutureBuilder<List<Detail>>(
                future: futureAlbum,
                builder: (context, snapshot){
              
                var result = snapshot.data;
                return ListView.builder(
        itemCount: result.length,
        itemBuilder: (context, index) {
          var project = result[index];
          return Text("${project.country}");
                 
                });
                }),
        ),*/
    ));*/}
