import 'package:flutter/material.dart';
import 'mainhome.dart';
void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: MainHome());
  }
}

/*Future<Autogenerated> fetchTimeSeri() async {
    
    var response = await http.get("https://pomber.github.io/covid19/timeseries.json");
    if (response.statusCode == 200) 
      {
          var responseJson = json.decode(response.body);
          return Autogenerated.fromJson(responseJson);
      }
      else {
    throw Exception('${response.statusCode}');
    
  }
  }
  Future<List<TimeSeri>> fetch() async {
    final response =
      await http.get('https://pomber.github.io/covid19/timeseries.json');
  
    if (response.statusCode == 200) {
     final jsonObject = json.decode(response.body) as Map;
     final object = jsonObject['Vietnam'];
      return object
        .map<TimeSeri>((json) => TimeSeri.fromJson(json))
        .toList(growable: false);
    
  } else {
    throw Exception('${response.statusCode}');
    
  }
}*/
/*Future<Map<String, dynamic>> fetc() async {
    final response =
      await http.get('https://pomber.github.io/covid19/timeseries.json');
  
    if (response.statusCode == 200) {
     final jsonObject = json.decode(response.body);
      return jsonObject;
    
  } else {
    throw Exception('${response.statusCode}');
    
  }
}*/
class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  /*
  Future<List<Detail>> futureAlbum;
HashMap afghanistan = new HashMap<String, dynamic>();
HashMap albania = new HashMap<String, dynamic>();
HashMap algeria = new HashMap<String, dynamic>();
HashMap andorra = new HashMap<String, dynamic>();
HashMap angola = new HashMap<String, dynamic>();
HashMap antigua = new HashMap<String, dynamic>();
HashMap argentina = new HashMap<String, dynamic>();
HashMap armenia = new HashMap<String, dynamic>();
HashMap australia = new HashMap<String, dynamic>();
HashMap austria = new HashMap<String, dynamic>();
HashMap azerbaijan = new HashMap<String, dynamic>();
HashMap bahamas = new HashMap<String, dynamic>();
HashMap bahrain = new HashMap<String, dynamic>();
HashMap bangladesh = new HashMap<String, dynamic>();
HashMap barbados = new HashMap<String, dynamic>();
HashMap belarus = new HashMap<String, dynamic>();
HashMap belgium = new HashMap<String, dynamic>();
HashMap benin = new HashMap<String, dynamic>();
HashMap bhutan = new HashMap<String, dynamic>();
HashMap bolivia = new HashMap<String, dynamic>();
HashMap bosnia = new HashMap<String, dynamic>();
HashMap brazil = new HashMap<String, dynamic>();
HashMap brunei = new HashMap<String, dynamic>();
HashMap bulgaria = new HashMap<String, dynamic>();
HashMap burkina = new HashMap<String, dynamic>();
HashMap cabo = new HashMap<String, dynamic>();
HashMap cambodia = new HashMap<String, dynamic>();
HashMap cameroon = new HashMap<String, dynamic>();
HashMap canada = new HashMap<String, dynamic>();
HashMap central = new HashMap<String, dynamic>();
HashMap chad = new HashMap<String, dynamic>();
HashMap chile = new HashMap<String, dynamic>();
HashMap china = new HashMap<String, dynamic>();
HashMap colombia = new HashMap<String, dynamic>();
HashMap congobra = new HashMap<String, dynamic>();
HashMap congokin = new HashMap<String, dynamic>();
HashMap costa = new HashMap<String, dynamic>();
HashMap cote = new HashMap<String, dynamic>();
HashMap croatia = new HashMap<String, dynamic>();
HashMap diamond = new HashMap<String, dynamic>();
HashMap cuba = new HashMap<String, dynamic>();
HashMap cyprus = new HashMap<String, dynamic>();
HashMap czechia = new HashMap<String, dynamic>();
HashMap denmark = new HashMap<String, dynamic>();
HashMap djibouti = new HashMap<String, dynamic>();
HashMap dominican = new HashMap<String, dynamic>();
HashMap ecuador = new HashMap<String, dynamic>();
HashMap egypt = new HashMap<String, dynamic>();
HashMap el = new HashMap<String, dynamic>();
HashMap equatorial = new HashMap<String, dynamic>();
HashMap eritrea = new HashMap<String, dynamic>();
HashMap estonia = new HashMap<String, dynamic>();
HashMap eswatini = new HashMap<String, dynamic>();
HashMap ethiopia = new HashMap<String, dynamic>();
HashMap fiji = new HashMap<String, dynamic>();
HashMap finland = new HashMap<String, dynamic>();
HashMap france = new HashMap<String, dynamic>();
HashMap gabon = new HashMap<String, dynamic>();
HashMap gambia = new HashMap<String, dynamic>();
HashMap georgia = new HashMap<String, dynamic>();
HashMap germany = new HashMap<String, dynamic>();
HashMap ghana = new HashMap<String, dynamic>();
HashMap greece = new HashMap<String, dynamic>();
HashMap guatemala = new HashMap<String, dynamic>();
HashMap guinea = new HashMap<String, dynamic>();
HashMap guyana = new HashMap<String, dynamic>();
HashMap haiti = new HashMap<String, dynamic>();
HashMap holy = new HashMap<String, dynamic>();
HashMap honduras = new HashMap<String, dynamic>();
HashMap hungary = new HashMap<String, dynamic>();
HashMap iceland = new HashMap<String, dynamic>();
HashMap india = new HashMap<String, dynamic>();
HashMap indonesia = new HashMap<String, dynamic>();
HashMap iran = new HashMap<String, dynamic>();
HashMap iraq = new HashMap<String, dynamic>();
HashMap ireland = new HashMap<String, dynamic>();
HashMap israel = new HashMap<String, dynamic>();
HashMap italy = new HashMap<String, dynamic>();
HashMap jamaica = new HashMap<String, dynamic>();
HashMap japan = new HashMap<String, dynamic>();
HashMap jordan = new HashMap<String, dynamic>();
HashMap kazakhstan = new HashMap<String, dynamic>();
HashMap kenya = new HashMap<String, dynamic>();
HashMap korea = new HashMap<String, dynamic>();
HashMap kuwait = new HashMap<String, dynamic>();
HashMap kyrgyzstan = new HashMap<String, dynamic>();
HashMap latvia = new HashMap<String, dynamic>();
HashMap lebanon = new HashMap<String, dynamic>();
HashMap liberia = new HashMap<String, dynamic>();
HashMap liechtenstein = new HashMap<String, dynamic>();
HashMap lithuania = new HashMap<String, dynamic>();
HashMap luxembourg = new HashMap<String, dynamic>();
HashMap madagascar = new HashMap<String, dynamic>();
HashMap malaysia = new HashMap<String, dynamic>();
HashMap maldives = new HashMap<String, dynamic>();
HashMap malta = new HashMap<String, dynamic>();
HashMap mauritania = new HashMap<String, dynamic>();
HashMap mauritius = new HashMap<String, dynamic>();
HashMap mexico = new HashMap<String, dynamic>();
HashMap moldova = new HashMap<String, dynamic>();
HashMap monaco = new HashMap<String, dynamic>();
HashMap mongolia = new HashMap<String, dynamic>();
HashMap montenegro = new HashMap<String, dynamic>();
HashMap morocco = new HashMap<String, dynamic>();
HashMap namibia = new HashMap<String, dynamic>();
HashMap nepal = new HashMap<String, dynamic>();
HashMap netherlands = new HashMap<String, dynamic>();
HashMap newzealand = new HashMap<String, dynamic>();
HashMap nicaragua = new HashMap<String, dynamic>();
HashMap niger = new HashMap<String, dynamic>();
HashMap nigeria = new HashMap<String, dynamic>();
HashMap north = new HashMap<String, dynamic>();
HashMap norway = new HashMap<String, dynamic>();
HashMap oman = new HashMap<String, dynamic>();
HashMap pakistan = new HashMap<String, dynamic>();
HashMap panama = new HashMap<String, dynamic>();
HashMap papua = new HashMap<String, dynamic>();
HashMap paraguay = new HashMap<String, dynamic>();
HashMap peru = new HashMap<String, dynamic>();
HashMap philippines = new HashMap<String, dynamic>();
HashMap poland = new HashMap<String, dynamic>();
HashMap portugal = new HashMap<String, dynamic>();
HashMap qatar = new HashMap<String, dynamic>();
HashMap romania = new HashMap<String, dynamic>();
HashMap russia = new HashMap<String, dynamic>();
HashMap rwanda = new HashMap<String, dynamic>();
HashMap saintlucia = new HashMap<String, dynamic>();
HashMap saintvincent = new HashMap<String, dynamic>();
HashMap san = new HashMap<String, dynamic>();
HashMap saudi = new HashMap<String, dynamic>();
HashMap senegal = new HashMap<String, dynamic>();
HashMap serbia = new HashMap<String, dynamic>();
HashMap seychelles = new HashMap<String, dynamic>();
HashMap singapore = new HashMap<String, dynamic>();
HashMap slovakia = new HashMap<String, dynamic>();
HashMap slovenia = new HashMap<String, dynamic>();
HashMap somalia = new HashMap<String, dynamic>();
HashMap southafrica = new HashMap<String, dynamic>();
HashMap spain = new HashMap<String, dynamic>();
HashMap sri = new HashMap<String, dynamic>();
HashMap sudan = new HashMap<String, dynamic>();
HashMap suriname = new HashMap<String, dynamic>();
HashMap sweden = new HashMap<String, dynamic>();
HashMap switzerland = new HashMap<String, dynamic>();
HashMap taiwan = new HashMap<String, dynamic>();
HashMap tanzania = new HashMap<String, dynamic>();
HashMap thailand = new HashMap<String, dynamic>();
HashMap togo = new HashMap<String, dynamic>();
HashMap trinidad = new HashMap<String, dynamic>();
HashMap tunisia = new HashMap<String, dynamic>();
HashMap turkey = new HashMap<String, dynamic>();
HashMap uganda = new HashMap<String, dynamic>();
HashMap ukraine = new HashMap<String, dynamic>();
HashMap unitedarab = new HashMap<String, dynamic>();
HashMap unitedkingdom = new HashMap<String, dynamic>();
HashMap uruguay = new HashMap<String, dynamic>();
HashMap us = new HashMap<String, dynamic>();
HashMap uzbekistan = new HashMap<String, dynamic>();
HashMap venezuela = new HashMap<String, dynamic>();
HashMap vietnam = new HashMap<String, dynamic>();
HashMap zambia = new HashMap<String, dynamic>();
HashMap zimbabwe = new HashMap<String, dynamic>();
HashMap dominica = new HashMap<String, dynamic>();
HashMap grenada = new HashMap<String, dynamic>();
HashMap mozambique = new HashMap<String, dynamic>();
HashMap syria = new HashMap<String, dynamic>();
HashMap timorleste = new HashMap<String, dynamic>();
HashMap belize = new HashMap<String, dynamic>();
HashMap laos = new HashMap<String, dynamic>();
HashMap libya = new HashMap<String, dynamic>();
HashMap west = new HashMap<String, dynamic>();
HashMap guineabissau = new HashMap<String, dynamic>();
HashMap mali = new HashMap<String, dynamic>();
HashMap saint = new HashMap<String, dynamic>();
HashMap kosovo = new HashMap<String, dynamic>();
HashMap burma = new HashMap<String, dynamic>();
HashMap ms = new HashMap<String, dynamic>();
HashMap botswana = new HashMap<String, dynamic>();
HashMap burundi = new HashMap<String, dynamic>();
HashMap sierra = new HashMap<String, dynamic>();
HashMap malawi = new HashMap<String, dynamic>();
HashMap southsudan = new HashMap<String, dynamic>();
HashMap western = new HashMap<String, dynamic>();
HashMap sao = new HashMap<String, dynamic>();
HashMap yemen = new HashMap<String, dynamic>();
HashMap comoros = new HashMap<String, dynamic>();
HashMap tajikistan = new HashMap<String, dynamic>();
HashMap lesotho = new HashMap<String, dynamic>();
Future<Map<String, dynamic>> fetc() async {
    final response =
      await http.get('https://pomber.github.io/covid19/timeseries.json');
  
    if (response.statusCode == 200) {
     final jsonObject = json.decode(response.body) as Map;
      return jsonObject;
    
  } else {
    throw Exception('${response.statusCode}');
    
  }
}*/
  @override
  void initState() {
    super.initState();
  }
    /*
  fetc().then((value) {
    for (var  i=0; i< value['Vietnam'].length; i++) {
afghanistan[value['Afghanistan'][i]['date']] = value['Afghanistan'][i];
albania[value['Albania'][i]['date']] = value['Albania'][i];
algeria[value['Algeria'][i]['date']] = value['Algeria'][i];
andorra[value['Andorra'][i]['date']] = value['Andorra'][i];
angola[value['Angola'][i]['date']] = value['Angola'][i];
antigua[value['Antigua and Barbuda'][i]['date']] = value['Antigua and Barbuda'][i];
argentina[value['Argentina'][i]['date']] = value['Argentina'][i];
armenia[value['Armenia'][i]['date']] = value['Armenia'][i];
australia[value['Australia'][i]['date']] = value['Australia'][i];
austria[value['Austria'][i]['date']] = value['Austria'][i];
azerbaijan[value['Azerbaijan'][i]['date']] = value['Azerbaijan'][i];
bahamas[value['Bahamas'][i]['date']] = value['Bahamas'][i];
bahrain[value['Bahrain'][i]['date']] = value['Bahrain'][i];
bangladesh[value['Bangladesh'][i]['date']] = value['Bangladesh'][i];
barbados[value['Barbados'][i]['date']] = value['Barbados'][i];
belarus[value['Belarus'][i]['date']] = value['Belarus'][i];
belgium[value['Belgium'][i]['date']] = value['Belgium'][i];
benin[value['Benin'][i]['date']] = value['Benin'][i];
bhutan[value['Bhutan'][i]['date']] = value['Bhutan'][i];
bolivia[value['Bolivia'][i]['date']] = value['Bolivia'][i];
bosnia[value['Bosnia and Herzegovina'][i]['date']] = value['Bosnia and Herzegovina'][i];
brazil[value['Brazil'][i]['date']] = value['Brazil'][i];
brunei[value['Brunei'][i]['date']] = value['Brunei'][i];
bulgaria[value['Bulgaria'][i]['date']] = value['Bulgaria'][i];
burkina[value['Burkina Faso'][i]['date']] = value['Burkina Faso'][i];
cabo[value['Cabo Verde'][i]['date']] = value['Cabo Verde'][i];
cambodia[value['Cambodia'][i]['date']] = value['Cambodia'][i];
cameroon[value['Cameroon'][i]['date']] = value['Cameroon'][i];
canada[value['Canada'][i]['date']] = value['Canada'][i];
central[value['Central African Republic'][i]['date']] = value['Central African Republic'][i];
chad[value['Chad'][i]['date']] = value['Chad'][i];
chile[value['Chile'][i]['date']] = value['Chile'][i];
china[value['China'][i]['date']] = value['China'][i];
colombia[value['Colombia'][i]['date']] = value['Colombia'][i];
congobra[value['Congo (Brazzaville)'][i]['date']] = value['Congo (Brazzaville)'][i];
congokin[value['Congo (Kinshasa)'][i]['date']] = value['Congo (Kinshasa)'][i];
costa[value['Costa Rica'][i]['date']] = value['Costa Rica'][i];
cote[value["Cote d'Ivoire"][i]['date']] = value["Cote d'Ivoire"][i];
croatia[value['Croatia'][i]['date']] = value['Croatia'][i];
diamond[value['Diamond Princess'][i]['date']] = value['Diamond Princess'][i];
cuba[value['Cuba'][i]['date']] = value['Cuba'][i];
cyprus[value['Cyprus'][i]['date']] = value['Cyprus'][i];
czechia[value['Czechia'][i]['date']] = value['Czechia'][i];
denmark[value['Denmark'][i]['date']] = value['Denmark'][i];
djibouti[value['Djibouti'][i]['date']] = value['Djibouti'][i];
dominican[value['Dominican Republic'][i]['date']] = value['Dominican Republic'][i];
ecuador[value['Ecuador'][i]['date']] = value['Ecuador'][i];
egypt[value['Egypt'][i]['date']] = value['Egypt'][i];
el[value['El Salvador'][i]['date']] = value['El Salvador'][i];
equatorial[value['Equatorial Guinea'][i]['date']] = value['Equatorial Guinea'][i];
eritrea[value['Eritrea'][i]['date']] = value['Eritrea'][i];
estonia[value['Estonia'][i]['date']] = value['Estonia'][i];
eswatini[value['Eswatini'][i]['date']] = value['Eswatini'][i];
ethiopia[value['Ethiopia'][i]['date']] = value['Ethiopia'][i];
fiji[value['Fiji'][i]['date']] = value['Fiji'][i];
finland[value['Finland'][i]['date']] = value['Finland'][i];
france[value['France'][i]['date']] = value['France'][i];
gabon[value['Gabon'][i]['date']] = value['Gabon'][i];
gambia[value['Gambia'][i]['date']] = value['Gambia'][i];
georgia[value['Georgia'][i]['date']] = value['Georgia'][i];
germany[value['Germany'][i]['date']] = value['Germany'][i];
ghana[value['Ghana'][i]['date']] = value['Ghana'][i];
greece[value['Greece'][i]['date']] = value['Greece'][i];
guatemala[value['Guatemala'][i]['date']] = value['Guatemala'][i];
guinea[value['Guinea'][i]['date']] = value['Guinea'][i];
guyana[value['Guyana'][i]['date']] = value['Guyana'][i];
haiti[value['Haiti'][i]['date']] = value['Haiti'][i];
holy[value['Holy See'][i]['date']] = value['Holy See'][i];
honduras[value['Honduras'][i]['date']] = value['Honduras'][i];
hungary[value['Hungary'][i]['date']] = value['Hungary'][i];
iceland[value['Iceland'][i]['date']] = value['Iceland'][i];
india[value['India'][i]['date']] = value['India'][i];
indonesia[value['Indonesia'][i]['date']] = value['Indonesia'][i];
iran[value['Iran'][i]['date']] = value['Iran'][i];
iraq[value['Iraq'][i]['date']] = value['Iraq'][i];
ireland[value['Ireland'][i]['date']] = value['Ireland'][i];
israel[value['Israel'][i]['date']] = value['Israel'][i];
italy[value['Italy'][i]['date']] = value['Italy'][i];
jamaica[value['Jamaica'][i]['date']] = value['Jamaica'][i];
japan[value['Japan'][i]['date']] = value['Japan'][i];
jordan[value['Jordan'][i]['date']] = value['Jordan'][i];
kazakhstan[value['Kazakhstan'][i]['date']] = value['Kazakhstan'][i];
kenya[value['Kenya'][i]['date']] = value['Kenya'][i];
korea[value['Korea, South'][i]['date']] = value['Korea, South'][i];
kuwait[value['Kuwait'][i]['date']] = value['Kuwait'][i];
kyrgyzstan[value['Kyrgyzstan'][i]['date']] = value['Kyrgyzstan'][i];
latvia[value['Latvia'][i]['date']] = value['Latvia'][i];
lebanon[value['Lebanon'][i]['date']] = value['Lebanon'][i];
liberia[value['Liberia'][i]['date']] = value['Liberia'][i];
liechtenstein[value['Liechtenstein'][i]['date']] = value['Liechtenstein'][i];
lithuania[value['Lithuania'][i]['date']] = value['Lithuania'][i];
luxembourg[value['Luxembourg'][i]['date']] = value['Luxembourg'][i];
madagascar[value['Madagascar'][i]['date']] = value['Madagascar'][i];
malaysia[value['Malaysia'][i]['date']] = value['Malaysia'][i];
maldives[value['Maldives'][i]['date']] = value['Maldives'][i];
malta[value['Malta'][i]['date']] = value['Malta'][i];
mauritania[value['Mauritania'][i]['date']] = value['Mauritania'][i];
mauritius[value['Mauritius'][i]['date']] = value['Mauritius'][i];
mexico[value['Mexico'][i]['date']] = value['Mexico'][i];
moldova[value['Moldova'][i]['date']] = value['Moldova'][i];
monaco[value['Monaco'][i]['date']] = value['Monaco'][i];
mongolia[value['Mongolia'][i]['date']] = value['Mongolia'][i];
montenegro[value['Montenegro'][i]['date']] = value['Montenegro'][i];
morocco[value['Morocco'][i]['date']] = value['Morocco'][i];
namibia[value['Namibia'][i]['date']] = value['Namibia'][i];
nepal[value['Nepal'][i]['date']] = value['Nepal'][i];
netherlands[value['Netherlands'][i]['date']] = value['Netherlands'][i];
newzealand[value['New Zealand'][i]['date']] = value['New Zealand'][i];
nicaragua[value['Nicaragua'][i]['date']] = value['Nicaragua'][i];
niger[value['Niger'][i]['date']] = value['Niger'][i];
nigeria[value['Nigeria'][i]['date']] = value['Nigeria'][i];
north[value['North Macedonia'][i]['date']] = value['North Macedonia'][i];
norway[value['Norway'][i]['date']] = value['Norway'][i];
oman[value['Oman'][i]['date']] = value['Oman'][i];
pakistan[value['Pakistan'][i]['date']] = value['Pakistan'][i];
panama[value['Panama'][i]['date']] = value['Panama'][i];
papua[value['Papua New Guinea'][i]['date']] = value['Papua New Guinea'][i];
paraguay[value['Paraguay'][i]['date']] = value['Paraguay'][i];
peru[value['Peru'][i]['date']] = value['Peru'][i];
philippines[value['Philippines'][i]['date']] = value['Philippines'][i];
poland[value['Poland'][i]['date']] = value['Poland'][i];
portugal[value['Portugal'][i]['date']] = value['Portugal'][i];
qatar[value['Qatar'][i]['date']] = value['Qatar'][i];
romania[value['Romania'][i]['date']] = value['Romania'][i];
russia[value['Russia'][i]['date']] = value['Russia'][i];
rwanda[value['Rwanda'][i]['date']] = value['Rwanda'][i];
saintlucia[value['Saint Lucia'][i]['date']] = value['Saint Lucia'][i];
saintvincent[value['Saint Vincent and the Grenadines'][i]['date']] = value['Saint Vincent and the Grenadines'][i];
san[value['San Marino'][i]['date']] = value['San Marino'][i];
saudi[value['Saudi Arabia'][i]['date']] = value['Saudi Arabia'][i];
senegal[value['Senegal'][i]['date']] = value['Senegal'][i];
serbia[value['Serbia'][i]['date']] = value['Serbia'][i];
seychelles[value['Seychelles'][i]['date']] = value['Seychelles'][i];
singapore[value['Singapore'][i]['date']] = value['Singapore'][i];
slovakia[value['Slovakia'][i]['date']] = value['Slovakia'][i];
slovenia[value['Slovenia'][i]['date']] = value['Slovenia'][i];
somalia[value['Somalia'][i]['date']] = value['Somalia'][i];
southafrica[value['South Africa'][i]['date']] = value['South Africa'][i];
spain[value['Spain'][i]['date']] = value['Spain'][i];
sri[value['Sri Lanka'][i]['date']] = value['Sri Lanka'][i];
sudan[value['Sudan'][i]['date']] = value['Sudan'][i];
suriname[value['Suriname'][i]['date']] = value['Suriname'][i];
sweden[value['Sweden'][i]['date']] = value['Sweden'][i];
switzerland[value['Switzerland'][i]['date']] = value['Switzerland'][i];
taiwan[value['Taiwan*'][i]['date']] = value['Taiwan*'][i];
tanzania[value['Tanzania'][i]['date']] = value['Tanzania'][i];
thailand[value['Thailand'][i]['date']] = value['Thailand'][i];
togo[value['Togo'][i]['date']] = value['Togo'][i];
trinidad[value['Trinidad and Tobago'][i]['date']] = value['Trinidad and Tobago'][i];
tunisia[value['Tunisia'][i]['date']] = value['Tunisia'][i];
turkey[value['Turkey'][i]['date']] = value['Turkey'][i];
uganda[value['Uganda'][i]['date']] = value['Uganda'][i];
ukraine[value['Ukraine'][i]['date']] = value['Ukraine'][i];
unitedarab[value['United Arab Emirates'][i]['date']] = value['United Arab Emirates'][i];
unitedkingdom[value['United Kingdom'][i]['date']] = value['United Kingdom'][i];
uruguay[value['Uruguay'][i]['date']] = value['Uruguay'][i];
us[value['US'][i]['date']] = value['US'][i];
uzbekistan[value['Uzbekistan'][i]['date']] = value['Uzbekistan'][i];
venezuela[value['Venezuela'][i]['date']] = value['Venezuela'][i];
vietnam[value['Vietnam'][i]['date']] = value['Vietnam'][i];
zambia[value['Zambia'][i]['date']] = value['Zambia'][i];
zimbabwe[value['Zimbabwe'][i]['date']] = value['Zimbabwe'][i];
dominica[value['Dominica'][i]['date']] = value['Dominica'][i];
grenada[value['Grenada'][i]['date']] = value['Grenada'][i];
mozambique[value['Mozambique'][i]['date']] = value['Mozambique'][i];
syria[value['Syria'][i]['date']] = value['Syria'][i];
timorleste[value['Timor-Leste'][i]['date']] = value['Timor-Leste'][i];
belize[value['Belize'][i]['date']] = value['Belize'][i];
laos[value['Laos'][i]['date']] = value['Laos'][i];
libya[value['Libya'][i]['date']] = value['Libya'][i];
west[value['West Bank and Gaza'][i]['date']] = value['West Bank and Gaza'][i];
guineabissau[value['Guinea-Bissau'][i]['date']] = value['Guinea-Bissau'][i];
mali[value['Mali'][i]['date']] = value['Mali'][i];
saint[value['Saint Kitts and Nevis'][i]['date']] = value['Saint Kitts and Nevis'][i];
kosovo[value['Kosovo'][i]['date']] = value['Kosovo'][i];
burma[value['Burma'][i]['date']] = value['Burma'][i];
ms[value['MS Zaandam'][i]['date']] = value['MS Zaandam'][i];
botswana[value['Botswana'][i]['date']] = value['Botswana'][i];
burundi[value['Burundi'][i]['date']] = value['Burundi'][i];
sierra[value['Sierra Leone'][i]['date']] = value['Sierra Leone'][i];
malawi[value['Malawi'][i]['date']] = value['Malawi'][i];
southsudan[value['South Sudan'][i]['date']] = value['South Sudan'][i];
western[value['Western Sahara'][i]['date']] = value['Western Sahara'][i];
sao[value['Sao Tome and Principe'][i]['date']] = value['Sao Tome and Principe'][i];
yemen[value['Yemen'][i]['date']] = value['Yemen'][i];
comoros[value['Comoros'][i]['date']] = value['Comoros'][i];
tajikistan[value['Tajikistan'][i]['date']] = value['Tajikistan'][i];
lesotho[value['Lesotho'][i]['date']] = value['Lesotho'][i];
    }
    value['Afghanistan'] = afghanistan;
value['Albania'] = albania;
value['Algeria'] = algeria;
value['Andorra'] = andorra;
value['Angola'] = angola;
value['Antigua and Barbuda'] = antigua;
value['Argentina'] = argentina;
value['Armenia'] = armenia;
value['Australia'] = australia;
value['Austria'] = austria;
value['Azerbaijan'] = azerbaijan;
value['Bahamas'] = bahamas;
value['Bahrain'] = bahrain;
value['Bangladesh'] = bangladesh;
value['Barbados'] = barbados;
value['Belarus'] = belarus;
value['Belgium'] = belgium;
value['Benin'] = benin;
value['Bhutan'] = bhutan;
value['Bolivia'] = bolivia;
value['Bosnia and Herzegovina'] = bosnia;
value['Brazil'] = brazil;
value['Brunei'] = brunei;
value['Bulgaria'] = bulgaria;
value['Burkina Faso'] = burkina;
value['Cabo Verde'] = cabo;
value['Cambodia'] = cambodia;
value['Cameroon'] = cameroon;
value['Canada'] = canada;
value['Central African Republic'] = central;
value['Chad'] = chad;
value['Chile'] = chile;
value['China'] = china;
value['Colombia'] = colombia;
value['Congo (Brazzaville)'] = congobra;
value['Congo (Kinshasa)'] = congokin;
value['Costa Rica'] = costa;
value["Cote d'Ivoire"] = cote;
value['Croatia'] = croatia;
value['Diamond Princess'] = diamond;
value['Cuba'] = cuba;
value['Cyprus'] = cyprus;
value['Czechia'] = czechia;
value['Denmark'] = denmark;
value['Djibouti'] = djibouti;
value['Dominican Republic'] = dominican;
value['Ecuador'] = ecuador;
value['Egypt'] = egypt;
value['El Salvador'] = el;
value['Equatorial Guinea'] = equatorial;
value['Eritrea'] = eritrea;
value['Estonia'] = estonia;
value['Eswatini'] = eswatini;
value['Ethiopia'] = ethiopia;
value['Fiji'] = fiji;
value['Finland'] = finland;
value['France'] = france;
value['Gabon'] = gabon;
value['Gambia'] = gambia;
value['Georgia'] = georgia;
value['Germany'] = germany;
value['Ghana'] = ghana;
value['Greece'] = greece;
value['Guatemala'] = guatemala;
value['Guinea'] = guinea;
value['Guyana'] = guyana;
value['Haiti'] = haiti;
value['Holy See'] = holy;
value['Honduras'] = honduras;
value['Hungary'] = hungary;
value['Iceland'] = iceland;
value['India'] = india;
value['Indonesia'] = indonesia;
value['Iran'] = iran;
value['Iraq'] = iraq;
value['Ireland'] = ireland;
value['Israel'] = israel;
value['Italy'] = italy;
value['Jamaica'] = jamaica;
value['Japan'] = japan;
value['Jordan'] = jordan;
value['Kazakhstan'] = kazakhstan;
value['Kenya'] = kenya;
value['Korea, South'] = korea;
value['Kuwait'] = kuwait;
value['Kyrgyzstan'] = kyrgyzstan;
value['Latvia'] = latvia;
value['Lebanon'] = lebanon;
value['Liberia'] = liberia;
value['Liechtenstein'] = liechtenstein;
value['Lithuania'] = lithuania;
value['Luxembourg'] = luxembourg;
value['Madagascar'] = madagascar;
value['Malaysia'] = malaysia;
value['Maldives'] = maldives;
value['Malta'] = malta;
value['Mauritania'] = mauritania;
value['Mauritius'] = mauritius;
value['Mexico'] = mexico;
value['Moldova'] = moldova;
value['Monaco'] = monaco;
value['Mongolia'] = mongolia;
value['Montenegro'] = montenegro;
value['Morocco'] = morocco;
value['Namibia'] = namibia;
value['Nepal'] = nepal;
value['Netherlands'] = netherlands;
value['New Zealand'] = newzealand;
value['Nicaragua'] = nicaragua;
value['Niger'] = niger;
value['Nigeria'] = nigeria;
value['North Macedonia'] = north;
value['Norway'] = norway;
value['Oman'] = oman;
value['Pakistan'] = pakistan;
value['Panama'] = panama;
value['Papua New Guinea'] = papua;
value['Paraguay'] = paraguay;
value['Peru'] = peru;
value['Philippines'] = philippines;
value['Poland'] = poland;
value['Portugal'] = portugal;
value['Qatar'] = qatar;
value['Romania'] = romania;
value['Russia'] = russia;
value['Rwanda'] = rwanda;
value['Saint Lucia'] = saintlucia;
value['Saint Vincent and the Grenadines'] = saintvincent;
value['San Marino'] = san;
value['Saudi Arabia'] = saudi;
value['Senegal'] = senegal;
value['Serbia'] = serbia;
value['Seychelles'] = seychelles;
value['Singapore'] = singapore;
value['Slovakia'] = slovakia;
value['Slovenia'] = slovenia;
value['Somalia'] = somalia;
value['South Africa'] = southafrica;
value['Spain'] = spain;
value['Sri Lanka'] = sri;
value['Sudan'] = sudan;
value['Suriname'] = suriname;
value['Sweden'] = sweden;
value['Switzerland'] = switzerland;
value['Taiwan*'] = taiwan;
value['Tanzania'] = tanzania;
value['Thailand'] = thailand;
value['Togo'] = togo;
value['Trinidad and Tobago'] = trinidad;
value['Tunisia'] = tunisia;
value['Turkey'] = turkey;
value['Uganda'] = uganda;
value['Ukraine'] = ukraine;
value['United Arab Emirates'] = unitedarab;
value['United Kingdom'] = unitedkingdom;
value['Uruguay'] = uruguay;
value['US'] = us;
value['Uzbekistan'] = uzbekistan;
value['Venezuela'] = venezuela;
value['Vietnam'] = vietnam;
value['Zambia'] = zambia;
value['Zimbabwe'] = zimbabwe;
value['Dominica'] = dominica;
value['Grenada'] = grenada;
value['Mozambique'] = mozambique;
value['Syria'] = syria;
value['Timor-Leste'] = timorleste;
value['Belize'] = belize;
value['Laos'] = laos;
value['Libya'] = libya;
value['West Bank and Gaza'] = west;
value['Guinea-Bissau'] = guineabissau;
value['Mali'] = mali;
value['Saint Kitts and Nevis'] = saint;
value['Kosovo'] = kosovo;
value['Burma'] = burma;
value['MS Zaandam'] = ms;
value['Botswana'] = botswana;
value['Burundi'] = burundi;
value['Sierra Leone'] = sierra;
value['Malawi'] = malawi;
value['South Sudan'] = southsudan;
value['Western Sahara'] = western;
value['Sao Tome and Principe'] = sao;
value['Yemen'] = yemen;
value['Comoros'] = comoros;
value['Tajikistan'] = tajikistan;
value['Lesotho'] = lesotho;
return Navigator.push(context, MaterialPageRoute(
            builder: (context) => Test(map: china)));
      }
      
      );   
  }*/
   @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        fit: StackFit.expand,
        children: <Widget>[
          Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              Container(
                padding: EdgeInsets.fromLTRB(0, 100, 0, 50),
                child: Image(
                  image: AssetImage('assets/images/meliquestreet_20200723_111219_0.jpg'),
                ),
              ),
              RichText(
                text: TextSpan(
                  style: TextStyle(
                    fontSize: 25.0,
                    fontWeight: FontWeight.bold,
                  ),
                  children: <TextSpan> [
                    TextSpan(
                        text: 'STAY ',
                        style: TextStyle(color: Colors.white)),
                    TextSpan(
                        text: 'HOME  ',
                        style: TextStyle(color: Colors.blueAccent)),
                    TextSpan(
                        text: 'STAY ',
                        style: TextStyle(color: Colors.white)),
                    TextSpan(
                        text: 'SAFE',
                        style: TextStyle(color: Colors.green)),
                  ]
                ),
              )
            ],
          )
        ],
      ),
    );
  }
  /*@override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("${vietnam['2020-1-22']['confirmed']}"),
        ),
        body: ListView.builder(
        itemCount: kkk.length,
        itemBuilder: (context, index) {
          var project = kkk[index];
          return Text(project);
                 
        })
       /* Center(
          child: FutureBuilder<List<Detail>>(
                future: futureAlbum,
                builder: (context, snapshot){
              
                var result = snapshot.data;
                return ListView.builder(
        itemCount: result.length,
        itemBuilder: (context, index) {
          var project = result[index];
          return Text("${project.country}");
                 
                });
                }),
        ),*/
    ));*/}
