import 'dart:async';
import 'package:flutter/material.dart';
import 'structure.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'mainhome.dart';
import 'timeseri.dart';
import 'complex.dart';
import 'api_complex.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: MyApp());
  }
}

Future<List<Detail>> fetchDetail() async {
    final response =
      await http.get('https://disease.sh/v3/covid-19/countries');
  
    if (response.statusCode == 200) {
     final jsonObject = json.decode(response.body);
      return jsonObject
        .map<Detail>((json) => Detail.fromJson(json))
        .toList(growable: false);
    
  } else {
    throw Exception('${response.statusCode}');
    
  }
}
Future<Autogenerated> fetchTimeSeri() async {
  ApiProvider _provider = ApiProvider();
    final response = await _provider.get();
    return Autogenerated.fromJson(response);
  }
class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final String val = "Afghanistan";
  Future<Autogenerated> futureAlbum;
  //List futureFlag ;
  @override
  void initState() {
    super.initState();
    futureAlbum = fetchTimeSeri();
    //futureFlag = getFlag();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data Example'),
        ),
        body: Center(
          child: FutureBuilder(
                future: futureAlbum,
                builder: (context, snapshot){
               
                var result = snapshot.data[val];
                return ListView.builder(
        itemCount: result.length,
        itemBuilder: (context, index) {
          var project = result[index];
          return Text("${project.date}");
                 
                });
                }),
        ),
    ));
  }
}